version: 2
updates:
- package-ecosystem: npm
  directory: "/templates/example_hello_world"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - mnmkng
  ignore:
  - dependency-name: apify
    versions:
    - 1.0.0
    - 1.0.1
- package-ecosystem: npm
  directory: "/templates/example_puppeteer_single_page"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - mnmkng
  ignore:
  - dependency-name: apify
    versions:
    - 1.0.0
    - 1.0.1
- package-ecosystem: npm
  directory: "/templates/project_cheerio_crawler"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - mnmkng
  ignore:
  - dependency-name: apify
    versions:
    - 1.0.0
    - 1.0.1
- package-ecosystem: npm
  directory: "/templates/project_empty"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - mnmkng
  ignore:
  - dependency-name: apify
    versions:
    - 1.0.0
    - 1.0.1
- package-ecosystem: npm
  directory: "/templates/project_puppeteer_crawler"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - mnmkng
  ignore:
  - dependency-name: apify
    versions:
    - 1.0.0
    - 1.0.1
- package-ecosystem: npm
  directory: "/templates/project_playwright_crawler"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - mnmkng
